# Generated by Django 2.1.7 on 2019-04-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_saldo_actual_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_de_la_categoria', to='presupuestos.Categoria'),
        ),
    ]
