# Generated by Django 2.1.7 on 2019-04-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_auto_20190408_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_de_la_categoria', to='presupuestos.Categoria'),
        ),
    ]
