# Generated by Django 2.1.7 on 2019-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre de la categoría')),
                ('planeado', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('diferencia', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre del presupuesto')),
                ('mes', models.DateField()),
                ('total_presupuestado', models.IntegerField()),
                ('total_real', models.IntegerField()),
            ],
        ),
    ]
