# Generated by Django 2.1.7 on 2019-03-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_auto_20190330_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='actual',
            field=models.IntegerField(blank=True),
        ),
    ]
