# Generated by Django 2.1.7 on 2019-03-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_auto_20190330_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='mes',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='total_real',
            field=models.IntegerField(null=True),
        ),
    ]
