# Generated by Django 2.1.7 on 2019-04-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_auto_20190330_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='tipo',
            field=models.CharField(choices=[('Egreso', 'Egreso'), ('Ingreso', 'Ingreso')], default='Egreso', max_length=20),
        ),
    ]
