# Generated by Django 2.1.7 on 2019-04-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0008_presupuesto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre del presupuesto'),
        ),
    ]
