# Generated by Django 2.1.7 on 2019-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre de la cuenta')),
                ('saldo', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito')], default='Debito', max_length=20)),
            ],
        ),
    ]
