# Generated by Django 2.1.7 on 2019-03-30 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuenta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_del_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
